### PR TITLE
Fpdt timestamps fix

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Before the changes, the ResetEnd value was out of scale:

```
FPDT: Boot Performance - ResetEnd                = 68719476758
FPDT: Boot Performance - OsLoaderLoadImageStart  = 489008239
FPDT: Boot Performance - OsLoaderStartImageStart = 564971805
FPDT: Boot Performance - ExitBootServicesEntry   = 1099163441
```

because it was incorrectly reported in tick instead of nano seconds. This caused the calculations in systemd-analyze to be invalid. After the changes the measurements look as follows:

```
ubuntu@3mdeb:~$ ls /sys/firmware/acpi/fpdt/boot/
bootloader_launch_ns  exitbootservice_end_ns    firmware_start_ns
bootloader_load_ns    exitbootservice_start_ns

ubuntu@3mdeb:~$ cat /sys/firmware/acpi/fpdt/boot/*
6704722126
6694814022
8964228680
8954010790
3814569

ubuntu@3mdeb:~$ sudo systemd-analyze
Startup finished in 6.704s (firmware) + 2.259s (loader) + 2.935s (kernel) + 5.313s (userspace) = 17.213s 
graphical.target reached after 5.240s in userspace
```

Value of 3814569 (firmware_start_ns/ResetEnd) matches the first timestamp reported with `cbmem -t`.  

Tested on MSI PRO Z690-A DDR5.

**Comment by miczyg1** [comment]
Accompanying PR: https://github.com/Dasharo/coreboot/pull/408

**Comment by pietrushnic** [comment]
@miczyg1 this is very cool, can we do a comparison with vendor firmware?

**Comment by miczyg1** [comment]
@pietrushnic tried with MSI firmware vA.E0, but it seems they released a tremendous crap. Ubuntu is slow as hell (or doesn't boot), yells PCIe hotplug errors, can't reboot (freezes instead) and firmware doesn't respect the bootorder I have set with efibootmgr... Even if I boot automatically to ubuntu, it takes forever for the boot to finish (some systems services are still waiting and systemd-analyze does not return results...)

**Comment by pietrushnic** [comment]
@miczyg1 thanks, I have to do some marketing with this.

**Comment by miczyg1** [comment]
@mkopec ping

**Review by mkopec — APPROVED** [review]

**Pull request merged**
