### PR TITLE
UefiPayloadPkg, DasharoModulePkg: update for extracted IOMMU settings

### PR DESCRIPTION
**Pull request by krystian-hebel**
This is done to allow building without edk2-platforms for platforms that don't need it.

Depends on https://github.com/Dasharo/DasharoModulePkg/pull/44

### CODE REVIEW

**Comment by miczyg1** [comment]
We need similar changes in QEMU

**Comment by krystian-hebel** [comment]
> We need similar changes in QEMU

https://github.com/Dasharo/dasharo-issues/issues/830#issuecomment-2131235066

**Comment by miczyg1** [comment]
> > We need similar changes in QEMU
> 
> [Dasharo/dasharo-issues#830 (comment)](https://github.com/Dasharo/dasharo-issues/issues/830#issuecomment-2131235066)

I don't understand this argumentation. We can at least make it build by guarding the VTD stuff or changing to the new DasharoBootPoliciesVTd.

I can't approve changes that break other builds.

**Comment by macpijan** [comment]
I assume the reasoning is, it does not make much sense to "fix" the OVMF build, if we will drop it in a moment.
So maybe we should be merging these QEMU changes into some integration branch, and as one of the steps (perhaps the last one) we will replace the CI build from OVMF to Dasharo (coreboot + edk2) for QEMU? In that way, we always have working builds in the `dasharo` branch.

**Comment by krystian-hebel** [comment]
Exactly as @macpijan said. There are still some issues to resolve before working image can be produced, and I'm OK with having integration branch until then.

In any case, new CI will probably have to live on coreboot repo, not here.

**Comment by SergiiDmytruk** [comment]
Integrated the changes into `rebased` branch:
 * cherry-picked 7d04eaa9d392b6764922523b3320035c8badd987
 * dropped https://github.com/Dasharo/edk2/commit/9386264b51a3077576ca4afec848f5b9dadb861f, so no need to revert it
 * updated 28402d1d7b1189f12a38b74da0ffb5f4116e0df7 to change DasharoPayloadPkg instead of UefiPayloadPkg

**Pull request closed without merging**
