### PR TITLE
WIP: Dasharo UEFI Secure Boot support in QEMU Q35

### LINKED ISSUE #550: Secure Boot Suite shall pass under QEMU

### PR DESCRIPTION
**Pull request by pietrushnic**
Fixes https://github.com/Dasharo/dasharo-issues/issues/550

Closes #104

### CODE REVIEW

**Comment by macpijan** [comment]
@pietrushnic Was anything missing in this MR?

**Comment by pietrushnic** [comment]
@macpijan this is not validated. Was stuck on OS installation from netboot.xyz, before I can pass the next test. I would focus on merging things related to iPXE. Here there is nothing more yet and I don't know if there will be if UEFi Secure Boot will work on #101 + miczyg's new UEFI Secure Boot.

**Comment by macpijan** [comment]
@pietrushnic So I guess we do not need this anymore? SB works for me from the main branch (except the keys are reset by default, which is different than on real HW).

**Comment by pietrushnic** [comment]
> @pietrushnic So I guess we do not need this anymore?

@macpijan most likely yes. So far I have not introduced any EDK II modifications related to secure boot, but we didn't test it comprehensively.

> except the keys are reset by default, which is different than on real HW

I don't understand that part. From what I see I can't enable secure boot if I do not reset keys which equals to provisioning default PK, db, dbx and KEK: https://docs.dasharo.com/dasharo-menu-docs/device-manager/#custom-mode-and-key-management)

**Comment by macpijan** [comment]
@pietrushnic 

> From what I see I can't enable secure boot if I do not reset keys

On the QEMU you cannot, on the hardware you can. The initial behavior is different, that the default keys on the HW are already provisioned after flashing.

**Comment by macpijan** [comment]
I could pass SB tests without these changes: https://github.com/Dasharo/open-source-firmware-validation/pull/118#issuecomment-1841613276

**Pull request closed without merging**
