### PR TITLE
SecureBootConfigDxe/SecureBootConfigImpl.c: add default for SB state

### PR DESCRIPTION
**Pull request by mkopec**
Fixes an issue where the setting would not be restored to the default value on pressing F9.

### CODE REVIEW

**Comment by macpijan** [comment]
It works, but only when F9 is pressed in Secure Boot menu - still some improvement is likely needed here

**Comment by mkopec** [comment]
@macpijan Fixed the Secure Boot setting not being restored and settings not being saved on reset - added a reminder to save (or discard) when selecting reset.

**Comment by macpijan** [comment]
Thanks. Tested in QEMU as well.

**Review by macpijan — APPROVED** [review]

**Comment by miczyg1** [comment]
Okay that seems to restore SB state. But what about keys? Are they restored to defaults? Also, if someone modified the keys and didn't enroll PK, setting SB state to enabled (if PcdSecureBootDefaultEnable is true/1) will fail.

**Pull request merged**
