### PR TITLE
DasharoPayloadPkg/PlatformBootManagerLib: Add missing BlParseLib in the INF file

### PR DESCRIPTION
**Pull request by miczyg1**
Fix build complaining on missing ParseVBootWorkbuf.

### CODE REVIEW

**Comment by krystian-hebel** [comment]
I don't see this complaint on Q35 with vboot enabled (I had to modify .fmd file for SMMSTORE and RO_FRID/RW_FWID_A sizes). How can I replicate the issue?

**Comment by miczyg1** [comment]
> I don't see this complaint on Q35 with vboot enabled (I had to modify .fmd file for SMMSTORE and RO_FRID/RW_FWID_A sizes). How can I replicate the issue?

I couldn't build the firmware for MinnowBoard Turbot [here](https://github.com/Dasharo/coreboot/pull/542), that's how it started.

**Comment by miczyg1** [comment]
@SergiiDmytruk if I am not mistaken, the PlatformBootManagerLib uses BlParseLib: https://github.com/Dasharo/edk2/blob/rebased/DasharoPayloadPkg/Library/PlatformBootManagerLib/PlatformBootManager.c#L16
ParseVBootWorkbuf is clearly a part of CbParseLib: https://github.com/Dasharo/edk2/blob/rebased/DasharoPayloadPkg/Library/CbParseLib/CbParseLib.c#L881

So my change should be correct. But I have no idea why all other platforms actually build, while MinnowMax not: https://github.com/Dasharo/coreboot/actions/runs/10264908984?pr=542

**Review by SergiiDmytruk — APPROVED** [review]
> But I have no idea why all other platforms actually build, while MinnowMax not

I don't think the build system enforces declarations in a strict way.  As long as something (directly or indirectly) used by a particular DXE mentions `BlParseLib` in its `.inf`-file, the DXE gets the library and there will be no error if you use it without a declaration.  The EDK2 configuration of MinnowMax probably results in `BlParseLib` not being mentioned at all in the dependency graph of `BdsDxe`, thus causing the error.

I saw the same happening with GUIDs: https://github.com/Dasharo/edk2-upstream/commit/357a7d54bb8604b536f08847e08fbbd3d5b973ec

**Pull request merged**
