### PR TITLE
Updated smmstore

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Fixes the random problems with SMMStore on Novacusto mADL laptops. Needs testing for all other platforms using UEFIPayload...

**Comment by macpijan** [comment]
> Needs testing for all other platforms using UEFIPayload...

So far tested on ADL laptops only?

**Comment by miczyg1** [comment]
@macpijan yup, I want to test Protectli VP46xx and MSI today as well.

**Comment by miczyg1** [comment]
Checked MSI DDR4 and VP4650 and it works. I think we may fairly assume that the driver update is more robust and some bugs have been fixed.

**Review by mkopec — APPROVED** [review]

**Pull request merged**
