### PR TITLE
Timeout default

### LINKED ISSUE #513: Auto Boot Time-out: If we press F9 (reset to default value) is reset to 0
### Device

protectli_vp4670

### Dasharo version

v1.1.0

### Affected component(s) or functionality

Auto Boot Time-out in Dasharo Menu

### Brief summary

If we press F9 (reset to default value) Auto Boot Time-out is reset to 0

### How reproducible

100%

### How to reproduce

Press F9 for Auto Boot Time-out

### Expected behavior

6(?) seconds.

### Actual behavior

0 second.

### Screenshots

_No response_

### Additional context

_No response_

### Solutions you've tried

_No response_

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Works on QEMU OVMF

**Comment by miczyg1** [comment]
@filipleple all that is left is to test it on target hardware to see if it works as intended. Then I think this PR may supersede #94

**Comment by miczyg1** [comment]
@filipleple will you test it anytime soon?

**Comment by filipleple** [comment]
@miczyg1 as soon as I manage to build it, on which I'm currently stuck - as mentioned in the task and during the daily meet

**Comment by miczyg1** [comment]
I managed to test it on MSI PRO Z690-A DDR4 and it worked.

**Pull request merged**
