### PR TITLE
UefiPayloadPkg/UefiPayloadPkg.dsc: Decrease s76 ec console verbosity

### PR DESCRIPTION
**Pull request by mkopec**
Make the EC console behave as a regular serial console.

### CODE REVIEW

**Comment by mkopec** [comment]
@miczyg1 ping

**Review by macpijan — APPROVED** [review]
I have verified that with this patch (and edk2 serial enabled) I was able to use the device in automated tests.

**Comment by miczyg1** [comment]
A good solution would be to AND the SYSTEM76_EC_LOGGING with `TARGET ==  DEBUG` so that when debug build is used, the EC console may act as debugging console as well.

**Comment by miczyg1** [comment]
@mkopec added a PR for that: https://github.com/Dasharo/edk2/pull/84

**Pull request merged**
