### PR TITLE
PlatformBootManager: handle Vboot EC errors

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by miczyg1** [comment]
LGTM, I will leave the message formula to @macpijan

**Comment by mkopec** [comment]
@macpijan ping

**Comment by macpijan** [comment]
How about:

```
Warning

It appears that firmware update process of the Embedded Controller has failed.
It is likely due to the AC adapter was not present. Please connect the AC
adapter, and boot the device again. 

If the AC adapter is connected, and the message persists after a few attempts,
please report this problem via one of the Dasharo support channels: https://docs.dasharo.com/#support

You may continue to use your device, although you may experience some issues
related to EC features (such as fan control, or function keys) if the EC
firmware version is not in sync with the main firmware.
```

@pietrushnic @BeataZdunczyk any thoughts?

**Comment by pietrushnic** [comment]
@macpijan, do you plan to add a support section on docs.dasharo.com? I don't feel like a decision-maker regarding UX in firmware; I'm too biased, and my opinion is forming based on community and customer feedback. The message looks ok to me. It is not scary, but if it is received correctly, we can probably only verify it in the field.

**Comment by BeataZdunczyk** [comment]
> How about:

LGTM @macpijan.

**Review by BeataZdunczyk — APPROVED** [review]

**Review by macpijan — APPROVED** [review]

**Pull request merged**
