### PR TITLE
UefiPayloadPkg/NetworkDrivers/ipxe.efi: Add menu with DTS integration

### PR DESCRIPTION
**Pull request by mkopec**
Menu script:

```
#!ipxe

# main menu
:MENU
menu
item --gap -- ------------------------ Dasharo Network Boot Menu ------------------------
item dasharo        Dasharo Tools Suite
item netbootxyz     OS installation (netboot.xyz official server)
item boot           Autoboot (DHCP)
item shell          iPXE Shell
choose --default dasharo --timeout 3000 target && goto ${target}

# main menu options
:dasharo
dhcp ||
chain https://boot.3mdeb.com/dts.ipxe ||
goto MENU

:netbootxyz
dhcp ||
chain https://boot.netboot.xyz/menu.ipxe ||
goto MENU

:boot
autoboot
goto MENU

:shell
echo You are now in iPXE shell. Type "exit" to go back to the main menu.
shell ||
goto MENU

autoboot
```

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
I would put the script here or add the link to the embedded script to the commit message or something...

**Comment by mkopec** [comment]
> I would put the script here or add the link to the embedded script to the commit message or something...

Right. Added to the PR message

**Comment by mkopec** [comment]
Menu updated as per mockup

**Comment by miczyg1** [comment]
If we have the final script file, it would be good to add as a file to the directory with ipxe.efi

**Comment by mkopec** [comment]
Added as `dasharo.ipxe` to the directory with ipxe.efi

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
