### PR TITLE
MdeModulePkg/Library/CustomizedDisplayLib: Fix hotkey positioning

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Before adding CrScreenshotDxe:
Screenshot from 2023-10-18 12-06-07
After adding CrScreenshotDxe:
Screenshot from 2023-10-18 12-27-51
After this PR:
Screenshot from 2023-10-18 12-24-44

**Comment by macpijan** [comment]
@miczyg1 Could you just confirm if menu parsing still works correctly with this change?

- running QEMU: https://github.com/Dasharo/open-source-firmware-validation/blob/rework-terminal-kwds/scripts/ci/qemu-run.sh
- running tests: https://github.com/Dasharo/open-source-firmware-validation/blob/rework-terminal-kwds/scripts/ci/qemu-self-test.sh#L3 (just the first one from this file should be enough, as it enters to the `Boot Maintenance Manager` menu)

You should use the specified branch, as this is still WIP.

Please provide log if you can, so we can see how the `boot_mgr_menu` looks like.

**Comment by miczyg1** [comment]
> @miczyg1 Could you just confirm if menu parsing still works correctly with this change?
> 
> * running QEMU: https://github.com/Dasharo/open-source-firmware-validation/blob/rework-terminal-kwds/scripts/ci/qemu-run.sh
> * running tests: https://github.com/Dasharo/open-source-firmware-validation/blob/rework-terminal-kwds/scripts/ci/qemu-self-test.sh#L3 (just the first one from this file should be enough, as it enters to the `Boot Maintenance Manager` menu)
> 
> You should use the specified branch, as this is still WIP.
> 
> Please provide log if you can, so we can see how the `boot_mgr_menu` looks like.

@macpijan All green: https://paste.dasharo.com/?80dee294c20b74a8#9VBi4vqXwQuSbTNqSfT4EJJzr7nV73AthyNrkrk6VMoq (unfortunately GH does not accept HTML files...)

**Comment by miczyg1** [comment]
But I can see that the checkpoint for obtaining menu construction is incorrect now: `${expected}='Esc=Exit'`.
It should be F9 hotkey to prevent catching the hotkey help.

Note that not all submenus display the hotkeys. It depends on the current form of currently highlighted option

**Review by macpijan — APPROVED** [review]
LGTM

**Pull request merged**
